### ISSUE TITLE
write_raw_bids does not include annotations that were added with mne to the BIDS output

### ISSUE THREAD

**Issue by neumann-wj** [mne-tools/mne-bids#332] opened 2019-12-11 21:33 UTC
#### Describe the bug
When I load a BrainVision EEG file and programatically add annotations on artifact locations, the write_raw_bids function does not include these information into the bids file. 

#### Steps to reproduce
rest_raw=mne.io.read_raw_brainvision(pth(data_path,rest_filename+'.vhdr'))
print(rest_raw.annotations)
$ <Annotations  |  2 segments : New Segment/ (1), DC Correction/ (1), orig_time : 2017-06-14 16:45:32.919734>
visual_artifacts =  mne.Annotations(onset=[5, 12, 107],duration=[1, 3, 3],description=['BAD_', 'BAD_', 'BAD_'],orig_time=rest_raw.annotations.orig_time)
rest_raw.set_annotations(rest_raw.annotations+visual_artifacts)
print(rest_raw.annotations)
$ <Annotations  |  5 segments : New Segment/ (1), BAD_ (3), DC Correction/ (1), orig_time : 2017-06-14 16:45:32.919734>
write_raw_bids(rest_raw, make_bids_basename(subject = '01',task='rest'), bids_path.as_posix(),overwrite=True)
bids_raw = read_raw_bids(make_bids_basename(subject = '01',task='rest')+'_eeg.vhdr',bids_path)

#### Expected results
I expected the annotations to be written into the BIDS container files. 

print(bids_raw.annotations)
$ <Annotations  |  5 segments : New Segment/ (1), BAD_ (3), DC Correction/ (1), orig_time : 2017-06-14 16:45:32.919734>

#### Actual results
But the annotations of the loaded file do not include the ones that I added:

print(bids_raw.annotations)
$<Annotations  |  2 segments : New Segment/ (1), DC Correction/ (1), orig_time : 2017-06-14 16:45:32.919734>

#### Additional information
I thought that a workaround could be to include events, event_id, but apparently mne does not add the new annotations to the output of mne.events_from_annotations(rest_raw).

**Comment by jasmainak** [comment] 2019-12-11 21:48
See the documentation here: https://mne.tools/mne-bids/generated/mne_bids.write_raw_bids.html#mne_bids.write_raw_bids.

The warning says that the original files are simply copied over. Whatever you change in the `raw.info` object reflects what will be written as metadata files. The original files are left untouched.

**Comment by agramfort** [comment] 2019-12-12 00:02
write_raw_bids can take events and event_id to be able to write events.
Annotations are not
in info so why not storing them on write? I think it's safe to do this no?

>

**Comment by jasmainak** [comment] 2019-12-12 00:44
The problem is that we don't have writers for most file formats. We can't do this consistently.

**Comment by agramfort** [comment] 2019-12-12 14:57
why? if I pass a raw that has raw.annotations I write it in the events
tsv. It does not require
having a writer.

**Comment by jasmainak** [comment] 2019-12-12 18:44
How would you read the data then? Do you read the annotations from the sidecar or the actual file? What gets precedence?

**Comment by agramfort** [comment] 2019-12-12 22:36
like what we do already when you pass events and event_id on write. On read
you take events.tsv and call _handle_events_reading.

makes sense?

>

**Comment by jasmainak** [comment] 2019-12-13 19:32
okay but you have annotations already in a brainvision file and then you read annotations from the sidecar. Which one do you choose or do you take the union of the two? That's why I say they should match, otherwise you are going in the direction of derivatives.

**Comment by agramfort** [comment] 2019-12-13 23:27
I would allow to pass annotations on write with an explicit parameter. Then
if you pass events, event_id
and annotations to write_raw_bids you put the union in events.tsv

then nothing changes in our reader. Makes sense?

>

**Comment by jasmainak** [comment] 2019-12-17 06:12
as long as users don't anticipate to "edit" the `raw.annotations` this is fine -- otherwise you could end up with duplicated copies of the same annotations.

**Comment by agramfort** [comment] 2019-12-17 07:44
here is a proposition

if  you pass events and or annotations to write_raw_bids it contains one or
both to put them in events.tsv

then on read if you have events.tsv it sets it as annotations. So there is
no duplication possible.

makes sense?

>

**Comment by hoechenberger** [comment] 2020-05-01 07:21
> if you pass events and or annotations to write_raw_bids it contains one or both to put them in events.tsv then on read if you have events.tsv it sets it as annotations. So there is no duplication possible.

I agree this is the sane approach and what I would expect as a user (with my -- granted -- limited experience with `mne-bids` so far).

**Comment by jasmainak** [comment] 2020-05-02 14:27
I'm sorry I got back to this late.

> then on read if you have events.tsv it sets it as annotations. So there is
no duplication possible.

I need to actually see the tests in a pull request to comment more. My feeling is that having two ways to write/read events could lead to unnecessary complexity and a mess. If you edit your `raw.annotations` to include a time shift for instance, but you don't pass that in the `events_id`, you will read in duplicated events but time shifted when reading them back in. You either say that we deprecate `events_data` and `event_id` and promote writing events with annotations, or you can stick to the current way of writing and its limitations.

**Comment by hoechenberger** [comment] 2020-05-02 17:34
> My feeling is that having two ways to write/read events could lead to unnecessary complexity and a mess. If you edit your `raw.annotations` to include a time shift for instance, but you don't pass that in the `events_id`, you will read in duplicated events but time shifted when reading them back in.

I'm not sure I fully understand or share your concern. If a users passes both, events and Annotations (attached to the Raw) to `write_bids_raw()`, we simply write the union of both. Passing `events` and `event_id` is already optional, so if a user has already addd their events to the Raw as Annotations, they can simply omit passing those values. I don't really see how this creates a mess?

**Comment by hoechenberger** [comment] 2020-05-02 17:36
> You either say that we deprecate `events_data` and `event_id` and promote writing events with annotations, or you can stick to the current way of writing and its limitations.

This also touches an interesting point I briefly discussed with @agramfort earlier today: that I believe it's kinda confusing the we have this differentiation between events and Annotations in MNE. But that's another issue (and should probably be discussed upstream…)

**Comment by jasmainak** [comment] 2020-05-02 18:55
Imagine the following script (not executable, just conceptual):

```py
events = mne.events_from_annotations(raw)
events[:, 2] += 100
write_raw_bids(raw, ..., events_data=events, ...)
raw = read_raw_bids(...)
events2 = mne.events_from_annotations(raw)
assert events2 == events
```
This will fail because you write union of `events` and `raw.annotations` during write, so when you read them back you get a different `raw.annotations`. This is unexpected behavior IMO. 

If you say you will not ever write `raw.annotations` but only use the `annotations` argument, then my objection is that why do you write `raw.info['sfreq']` but not `raw.annotations`? Not saying that it's not possible to fix it, just saying we need clear behavior without surprises.

ps: saving artifacts as annotations is not exactly supported by BIDS yet. It's borderline BIDS derivative (c.f., BEP021). It's what some would call an "enriched events" file. But I'm fine supporting it if helps some users.

**Comment by hoechenberger** [comment] 2020-05-02 19:12
> ```python
> events = mne.events_from_annotations(raw)
> events[:, 2] += 100
> write_raw_bids(raw, ..., events_data=events, ...)
> raw = read_raw_bids(...)
> events2 = mne.events_from_annotations(raw)
> assert events2 == events
> ```

Ok I see the issue now. I agree: resorting to allow annotations _only_ would be the cleanest approach here. However this kind of clashes with common MNE workflows / MNE users' expectations, I'm afraid…

There could be an additional kwarg `merge_events=False`, maybe? If `True`, it would unionize Annotations and events.

**Comment by agramfort** [comment] 2020-05-02 19:21
the natural structure to read in the events from a bids perspective (onset,
duration, description) is an Annotations.
When you pass events and event_id to write_raw_bids the only way to get it
back with read_raw_bids is via an Annotations.
So to me we already pass events in and get Annotations out.
If raw has already annotations you should get them back and if you pass
events for a raw that has annotations should
get both. It's the most natural behavior for me.

**Comment by hoechenberger** [comment] 2020-05-02 19:27
Maybe @jasmainak's concern can simply be addressed via a big fat red box in the documentation?

**Comment by hoechenberger** [comment] 2020-05-02 19:27
> If raw has already annotations you should get them back and if you pass
> events for a raw that has annotations should
> get both. It's the most natural behavior for me.

+1

**Comment by jasmainak** [comment] 2020-05-02 19:48
if annotations is the natural structure and you read annotations anyway, why not deprecate `events_data` and `event_id`?

**Comment by jasmainak** [comment] 2020-05-02 19:50
To me, it's just wrong to do processing during IO. What you write should be what you read in. It's a bit like constructing an artificial stimulus channel which caused so much confusion in MNE

**Comment by hoechenberger** [comment] 2020-05-02 20:24
> if annotations is the natural structure and you read annotations anyway, why not deprecate `events_data` and `event_id`?

Because on the MNE end, what people get and work with for managing events are … events, and not `Annotations`. I wholeheartedly agree that this is confusing (but there are different opinions *looks to @agramfort and winks*)

Question is, do we want to impose a "change of thought" on users when they want to export their data from MNE to BIDS via `mne-bids`, or do we want to support their current workflows / expectations as good as we can. I think the events <> `Annotations` thing should be addressed upstream… There's, in fact, already an issue on that: https://github.com/mne-tools/mne-python/issues/6018

_Or_, as a compromise that would allow us to move forward more quickly: We could provide a convenience function, `events_to_annotations()`, and deprecate `events` and `event_id` altogether. Inspiration can be found in this tutorial: https://mne.tools/dev/auto_tutorials/intro/plot_20_events_from_raw.html#converting-between-events-arrays-and-annotations-objects

WDYT?

**Comment by jasmainak** [comment] 2020-05-02 20:43
I think either way, it's a change of behavior for `mne-bids` users because so far we did not use the `raw.annotations` to write to events.tsv.

Giving users functions to convert from events to annotations is fine by me.  It's just more clear and explicit. In fact, it's a clear cue to tell them -- hey you're entering BIDS territory now, so start using annotations. Silently merging the events and annotations when reading or writing seems dangerous.

**Comment by agramfort** [comment] 2020-05-02 21:07
but we already have a pb no @jasmainak? we pass events and event_id and we
get Annotations.
Should we read back events we would loose the descriptions of events and I
would not know
where to store this info in meas info. I would not want to use/create a
stim channel

>

**Comment by jasmainak** [comment] 2020-05-02 21:44
yes, so just write annotations and read back annotations always? No events and event_id is what I'm proposing.

**Comment by neumann-wj** [comment] 2020-05-04 10:39
> 
> 
> okay but you have annotations already in a brainvision file and then you read annotations from the sidecar. Which one do you choose or do you take the union of the two? That's why I say they should match, otherwise you are going in the direction of derivatives.

It think BIDS expects derivatives, when it comes to defining artefacts and definition of good and bad channels. Basically, you want to store and share data that can be programmatically cleaned. I am mostly worried about the way artefacts are handled. I don't want to do it every time I use the data.

**Comment by hoechenberger** [comment] 2020-05-04 10:42
> It think BIDS expects derivatives, when it comes to defining artefacts and definition of good and bad channels. Basically, you want to store and share data that can be programmatically cleaned. I am mostly worried about the way artefacts are handled. I don't want to do it every time I use the data.

So what do you suggest? :)

**Comment by neumann-wj** [comment] 2020-05-04 11:24
Thank you all for this discussion on my issue. I absolutely agree with all the points made. I do think it is crucial that data can be stored in a programatically cleanable way. 

I believe that researchers throughout the world are currently using MNE to convert their files to BIDS and I think it would be a significant contribution to this effort, if you could accomodate any changes that help with this. 

Re: Annotations: My personal favorite would be to read all events as annotations before new annotations can be added and then write out the latest version of the annotations when writing out bids folders. 

Another issue is the data file format. Would it not be possible to include a way to store the datasets in BrainVision or edf format that were prepared in BIDS? *With prepared I mean: Read in (e.g. from any proprietary format, annotated for artefacts, corrected for channel name / condition name irregularities, corrected / trigger / event mix ups). 

I work in invasive neurophysiology, both intraop and postop and no experiment ever is good after recording. I have to clean up a lot of things that went wrong in each recording before the dataset is good to go. I would love a way to do all this in BIDS and then write out as BIDS conform BrainVision file alongside added annotations.

**Comment by jasmainak** [comment] 2020-05-04 16:00
Hi @neumann-wj  regarding annotations, please do look at [BEP 021](https://docs.google.com/document/d/1PmcVs7vg7Th-cGC-UrX8rAhKUHIzOI-uIOh69_mvdlw/edit?usp=sharing) if you haven't already. We also sent out a [survey](https://forms.gle/k8qpW1ddyk4Hqh5q8) some time back to understand what people need. Unfortunately, this has lost steam because I had other priorities take precedence. 

I think events and annotations are different in the sense that events allow you to construct epochs and are unambiguous. On the other hand, annotations are "labels" that could be generated with a computer algorithm or be subjective and differ depending on the data curator. You could have multiple annotations for a raw file but only a single events file. Maybe all the confusion we had above is due to this.

We do support writing to brainvision but only when the data is anonymized. Perhaps this could be expanded to the case when the original data was in brainvision format. The writer for brainvision is beginning to mature thanks to efforts by @sappelhoff .

**Comment by hoechenberger** [comment] 2021-11-14 19:50
Closing, but feel free to reopen.

**Closed by hoechenberger** 2021-11-14 19:50 UTC
