### ISSUE TITLE
[BUG] empty files not allowed

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids#131] opened 2018-11-13 04:56 UTC
Travis is failing with the following message:

```sh
1: [ERR] Empty files not allowed. (code: 99 - EMPTY_FILE)
		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds/BadChannels
		./sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.ds/bad.segments
```

also there is a warning:

```sh
	1: [WARN] Tabular file contains custom columns not described in a data dictionary (code: 82 - CUSTOM_COLUMN_WITHOUT_DESCRIPTION)
```

which needs to be fixed

**Comment by sappelhoff** [comment] 2018-11-13 16:57
For fixing the empty files, we could write some garbage into the files for the tests. What do you think?

The participants.json is an easy fix, I could do it soonish.

**Comment by jasmainak** [comment] 2018-11-13 17:00
yeah that sounds great !

**Comment by monkeyman192** [comment] 2018-11-13 22:20
I don't know much about the CTF format, but *why* are the files empty? Are they empty because there is relevant data to fill them? In which case could this also not happen when actually converting real data?

**Comment by jasmainak** [comment] 2018-11-13 22:37
I agree with @monkeyman192 . We should investigate why the files are actually empty ...

**Comment by sappelhoff** [comment] 2018-11-14 08:35
for convenience, quick link to the error log: https://travis-ci.org/mne-tools/mne-bids/jobs/454584228

**Comment by sappelhoff** [comment] 2018-11-14 08:40
The issue is that the testing data we are using contains empty files. these empty files are then copied over. See:

```bash
appelhoff@p51:~/mne_data/MNE-testing-data/CTF/testdata_ctf.ds$ ls -lah
total 20M
drwxrwxr-x 2 appelhoff appelhoff 4.0K Oct 18 12:06 .
drwxrwxr-x 9 appelhoff appelhoff 4.0K Oct 18 12:06 ..
-rwxrwxr-x 1 appelhoff appelhoff    0 Oct 18 12:06 BadChannels
-rwxrwxr-x 1 appelhoff appelhoff    0 Oct 18 12:06 bad.segments
-rwxrwxr-x 1 appelhoff appelhoff  186 Oct 18 12:06 ClassFile.cls
-rwxrwxr-x 1 appelhoff appelhoff  467 Oct 18 12:06 params.dsc
-rwxrwxr-x 1 appelhoff appelhoff 1.2K Oct 18 12:06 processing.cfg
-rwxrwxr-x 1 appelhoff appelhoff  40K Oct 18 12:06 testdata_ctf.acq
-rwxrwxr-x 1 appelhoff appelhoff  824 Oct 18 12:06 testdata_ctf.hc
-rwxrwxr-x 1 appelhoff appelhoff 2.6K Oct 18 12:06 testdata_ctf.infods
-rwxrwxr-x 1 appelhoff appelhoff  17M Oct 18 12:06 testdata_ctf.meg4
-rwxrwxr-x 1 appelhoff appelhoff  350 Oct 18 12:06 testdata_ctf.newds
-rwxrwxr-x 1 appelhoff appelhoff 3.2M Oct 18 12:06 testdata_ctf.res4
```

Note BadChannels and bad.Segments.

For a fix, we could either take different testing data, or apply the decorator I started in #132 to the `write_raw_bids` function within the scope of the `test_ctf` exclusively:

https://github.com/mne-tools/mne-bids/blob/828778d5ec876f21c99d50157ab1057e33f46c69/mne_bids/tests/test_mne_bids.py#L150-L165

**Comment by agramfort** [comment] 2018-11-14 08:51
it's perfectly normal to have no bad channels or bad segments but maybe you
can delete the files when you detect they are empty? I mean just for testing

**Comment by jasmainak** [comment] 2018-11-14 18:52
yes I agree with @agramfort . It's quite normal to have no bad channels. Maybe something to fix in validator?

**Comment by jasmainak** [comment] 2018-11-14 18:53
But I would suggest not using bleeding edge version of validator ...

**Comment by sappelhoff** [comment] 2018-11-14 19:06
If  the `BadChannels` and `bad.Segments` files are part of the CTF data and they get written even if no bad channels or bad segments are present, ... then we have to have a "special rule" for CTF in the bids validator.

regarding bleeding edge version: yes, the validator is also released quite regularly (once a month?) ... we could try to always have the most recent release in MNE and then do a "once a month error catching" of the errors that are introduced through changes in the validator

**Comment by agramfort** [comment] 2018-11-14 20:03
you have 2 options:

- fix CTF datasets
- make an exception in validator

if validator is put in production then people will not be able to upload so
pb will fix itself eventually....

**Comment by jasmainak** [comment] 2018-11-14 20:16
yeah, either route is fine I think ...

**Comment by sappelhoff** [comment] 2018-11-14 20:35
I like the "gonna fix itself" idea ;-) but I raised an issue anyways. Let's hope sombody else picks it up: https://github.com/bids-standard/bids-validator/issues/651

What should we do with #132 meanwhile? Should I close it?

**Comment by jasmainak** [comment] 2018-11-14 20:37
you could just update the PR so we don't use bleeding edge validator or you could just remove these two files in the tests before running the validator ...

**Closed** 2018-11-20 07:05 UTC
Labels: bug
