### ISSUE TITLE
Recent addition to bids-validator breaks our tests

### ISSUE THREAD

**Issue by sappelhoff** [mne-tools/mne-bids#459] opened 2020-06-23 17:49 UTC
@adam2392 implemented a new check in the bids-validator: https://github.com/bids-standard/bids-validator/pull/976

in brief, it checks whether each entry in a `scans.tsv` file refers to an actual file that exists.

Since that PR was merged, our CIs break: https://github.com/mne-tools/mne-bids/runs/800358772

**Comment by adam2392** [comment] 2020-06-23 18:02
This looks like it's happening from "manual" removals of data files. At least for what you linked, it looks like:

test_fif::182 causes the problem.
```
        os.remove(op.join(bids_root, 'test-raw.fif'))
```

Been procrastinating the PR #443, but now it seems that is more necessary if one wants to remove "scans" safely.

**Comment by sappelhoff** [comment] 2020-06-23 18:04
> Been procrastinating the PR #443, but now it seems that is more necessary if one wants to remove "scans" safely.

yes, #443 would be a neat way to both fix the current tests, and test #443 itself :)

**Comment by agramfort** [comment] 2020-06-23 19:38
PR welcome :)

>

**Comment by adam2392** [comment] 2020-06-24 16:00
Actually, it looks like the problem is from the `.pdf` BTI data in [specification](https://bids-specification.readthedocs.io/en/stable/99-appendices/06-meg-file-formats.html#bti4d-neuroimaging). So it is not due to #433 actually...

The validator error:
```
1: [ERR] The filename in scans.tsv file does not match what is present in the BIDS dataset. (code: 129 - SCANS_FILENAME_NOT_MATCH_DATASET)

		./sub-01/ses-01/sub-01_ses-01_scans.tsv

			@ line: 1

			Evidence: Filename: /sub-01/ses-01/meg/sub-01_ses-01_task-testing_acq-01_run-01_meg/sub-01_ses-01_task-testing_acq-01_run-01_meg.pdf
```

The corresponding lines that that file is written is: https://github.com/mne-tools/mne-bids/blob/6fb4a0d3ec060da2a3cf0e0bc78ec60af2813272/mne_bids/write.py#L1163-L1164

Either the scans.tsv output `filename` for that type of file needs to be adjusted, or the actual file path to which this "BTI" dataset is written needs to be adjusted? Idk what BTI data is, so perhaps someone can chime in if there's an easy fix and I can add it into #433?

**Comment by jasmainak** [comment] 2020-06-24 17:10
`.pdf` appears to be an invalid extension. BTi data doesn't have an extension as far as I remember. It was just a hack because some parts of our code need an extension to triage

**Comment by adam2392** [comment] 2020-06-26 01:38
Once https://github.com/bids-standard/bids-validator/pull/1005 is merged, this will get fixed, and then hopefully #443 and #457 can get finished up!

Tested it out locally and one error due to some weird setting on my computer that I can't figure out, but no errors due to `bids-validator`.
```
===================================================================================== short test summary info =====================================================================================
FAILED mne_bids/tests/test_read.py::test_get_matched_emptyroom_no_meas_date - Failed: DID NOT WARN. No warnings of type (<class 'RuntimeWarning'>,) matching ('Could not retrieve .* date') was ...
======================================================================= 1 failed, 82 passed, 1 warning in 81.50s (0:01:21) ========================================================================
(mne) adam2392@Adams-MacBook-Pro-3 mne-bids % 
```

**Comment by jasmainak** [comment] 2020-06-26 02:02
@adam2392 the last error might be due to mismatch in MNE-Python version

**Comment by jasmainak** [comment] 2020-06-28 04:47
any progress on fixing the CIs yet? I think we should prioritize that

**Comment by sappelhoff** [comment] 2020-06-28 07:32
> any progress on fixing the CIs yet? I think we should prioritize that

I think it needs to be fixed in bids-validator. 

there are https://github.com/bids-standard/bids-validator/issues/1002 and https://github.com/bids-standard/bids-validator/issues/1005 that @adam2392 is working on

**Comment by jasmainak** [comment] 2020-06-30 05:27
looks like the validator PR is merged now :-)

**Comment by sappelhoff** [comment] 2020-06-30 06:53
yet it did not fix the CIs :thinking: I just re-ran them to be sure.

**Comment by adam2392** [comment] 2020-06-30 13:00
> yet it did not fix the CIs 🤔 I just re-ran them to be sure.

Need to add the fixes I added in `write.py` in https://github.com/mne-tools/mne-bids/pull/457 ;)

**Comment by jasmainak** [comment] 2020-06-30 18:07
@adam2392 can we make a separate PR for the CIs? Because #457 might take a while!

**Closed** 2020-06-30 18:46 UTC
Labels: bids-validator
