### ISSUE TITLE
Change arg order to make `kind` a required field

### ISSUE THREAD

**Issue by teonbrooks** [mne-tools/mne-bids#66] opened 2018-08-12 16:05 UTC
We shouldn't assume a default file type. I propose moving the `kind` arg up and making it the fifth required field. Also remove the default that is currently `meg`.

**Comment by jasmainak** [comment] 2018-08-13 02:34
Could we not infer it directly from the `info` object?

**Comment by teonbrooks** [comment] 2018-08-14 13:51
we use it internally to make sure we are pulling modality-specific channels and info. I think inferring would be problematic with files with combined `eeg`and `meg`. also, there are some differences in the json writing for meg versus eeg so I think it would be better to remain explicit

**Comment by teonbrooks** [comment] 2018-08-15 05:11
as well as we are able to swap among the metadata files appropriately and it works seamless, i would be OK with the kind argument going away. we would need to decide before release otherwise we will be breaking api 🙃

**Comment by sappelhoff** [comment] 2018-08-15 08:35
> As for differences between EEG vs MEG, won't they be ironed out before the extensions are merged into the main spec?

However, there will probably always be slight differences, such as different `coordinates.json` files between MEG, EEG, and iEEG. --> a "kind" argument would allow us to handle these very easily and explicitly.

**Comment by jasmainak** [comment] 2018-10-17 04:34
@teonbrooks let's close this issue as it's a duplicate of #73 and #105 ?

**Closed** 2018-10-17 15:03 UTC
