### ISSUE TITLE
Issues with overriding

### ISSUE THREAD

**Issue by monkeyman192** [mne-tools/mne-bids#42] opened 2018-06-06 04:05 UTC
The override=True parameter for raw_to_bids is a bit problematic.
By default it will delete another folder of bids data if it is a different acquisition, but same session.
I get that it is meant to be used to allow data to be well... overridden, however it has unintended side-effects.
For files the effect is fine and works as intended.
I think override should either be False by default (seems unnecessary to have to specify something like that), or make some kind of check to see if any parameters other than session and subject are provided, and if so set the folder override to False (otherwise any data with different task, acq, or any other optional parameter with same session/subject will be deleted)

**Comment by agramfort** [comment] 2018-06-06 10:27
+1 for override=False by default

**Comment by jasmainak** [comment] 2018-06-06 11:12
okay agreed

**Comment by monkeyman192** [comment] 2018-06-08 02:11
There will still be a problem if you want to override the data in the folder with new session/acquisition data, but not override other data that already exists with different parameters in the same folder (ie. different acquisition values)

**Comment by jasmainak** [comment] 2018-06-08 13:38
you mean folder should not be recreated? I agree that should how it should work by default

**Comment by choldgraf** [comment] 2018-06-08 23:45
+1 on a PR to make the overwriting a bit more granular than deleting the whole folder. Wanna give it a shot @monkeyman192 ?

**Comment by jasmainak** [comment] 2018-09-22 03:56
This appears to be a duplicate of #82. Can we close one of these @monkeyman192 @sappelhoff ?

**Comment by sappelhoff** [comment] 2018-09-22 05:46
+1, let's close this one - the proposals in #82 are more concrete

**Closed by sappelhoff** 2018-09-22 05:46 UTC
Labels: API
